# Generated by Django 3.2.7 on 2021-09-22 14:19

from django.db import migrations, models
import phonenumber_field.modelfields
import subs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='name')),
                ('lastname', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True, verbose_name='phone')),
                ('valid', models.BooleanField(default=True, verbose_name='valid')),
                ('domain', models.CharField(max_length=100, validators=[subs.models._simple_domain_name_validator], verbose_name='domain name')),
                ('other', models.CharField(blank=True, max_length=255, verbose_name='Other info')),
            ],
            options={
                'verbose_name': 'subscriber',
                'verbose_name_plural': 'subscribers',
            },
        ),
    ]
